Make error associated with material api level more readable
If a material is using an api that requires 2 but uses api level of 1, it fails to compile with ERROR 'apiName' : no matching overloaded function found.
The error message is not very straightfoward, so this PR makes the error message more readable.

For example,
ERROR: 0:9: 'getWorldRayFromClip' : no matching overloaded function found
is now
ERROR: 0:9: getWorldRayFromClip requires api level 2

To make this work, any new api that is introduced should be wrapped with
/**
 * @api-level 2
 */
void myNewFeature() {...}